# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://BetaLeaf.net
title: BetaLeaf.net
author: Jeff Savage
iauthor: BetaLeaf
description: Virus Removal Service and Software
avatar: Avatar2.png
phone: 18593598373
sms: 18593598373
email: Jeff@BetaLeaf.net
github: BetaLeaf
twitter: BetaLeafNet
facebook: BetaLeaf
steam: BetaLeaf
discord: eRgxT

#Comment out if you don't want disqus 
disqus: betaleafnet
google_analytics: UA-77915524-1


# needed for travis-ci build
exclude: [vendor]
