# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://betaleaf.net
title: BetaLeaf
author: BetaLeaf
description: Personal blog
avatar: Avatar.png
email: BetaLeaf@gmail.com
github: BetaLeaf
twitter: BetaLeafNet
#Comment out if you don't want disqus 
disqus: betaleafnet
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
