# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://betaleaf.net
coreurl: betaleaf.net
title: BetaLeaf
author: BetaLeaf
authorRN: Jeff Savage
description: Personal blog
avatar: Avatar.png
email: BetaLeaf@gmail.com
github: BetaLeaf
twitter: BetaLeafNet
facebook: BetaLeaf
steam: BetaLeaf

#Comment out if you don't want disqus 
disqus: betaleafnet
google_analytics: UA-77915524-1


# needed for travis-ci build
exclude: [vendor]
